### ISSUE TITLE
Process to create library using MSnbase fails 

### ISSUE THREAD

**Issue by maxvincent24** [nf-core/metaboigniter#48]
## Description of the bug

In the identification subpipeline, I am trying to perform the identification using internal standards. I have a few library .mzML files and an associated library description file. The process _process_create_library_pos_msnbase_ fails gives different errors when different values of the following parameters are set in the _conf/parameters.config_ file:
```
raw_file_name_preparelibrary_pos_msnbase
compund_id_preparelibrary_pos_msnbase
compound_name_preparelibrary_pos_msnbase
mz_col_preparelibrary_pos_msnbase
```

## Steps to reproduce

Sorry the data cannot be given to reproduce the error :(

1. Command line: `nextflow run metaboigniter/main.nf
		 -c metaboigniter/conf/custom.config
		 -profile singularity`

2. Log file:
[log.txt](https://github.com/nf-core/metaboigniter/files/7170423/log.txt) (.nextflow.log renamed in log.txt)

3. System:
- Hardware: HPC
- Executor: slurm
- OS: CentOS Linux
- Version: 7

4. Nextflow Installation:
- Version: 20.10.0

5. Container engine:
- Engine: Singularity
- version: 3.7.4-1.el7
- Image tag: nfcore/metaboigniter:1.0.1

## Errors

I found that when we set the parameters (these following four with values different than default) :
```
raw_file_name_preparelibrary_pos_msnbase = 'RAW_FILE'
compund_id_preparelibrary_pos_msnbase = 'IARC_ID'
compound_name_preparelibrary_pos_msnbase = 'NAME'
mz_col_preparelibrary_pos_msnbase = 'MZ'
```
the process _process_create_library_pos_msnbase_ fails with the error :
```
Loading required package: stringr
  Error in `[.data.frame`(libraryInfo, , requiredHeader["mzCol"]) : 
    undefined columns selected
  Calls: createLibrary -> IntervalMerge -> [ -> [.data.frame
  Execution halted
```
 
When we set the parameter for mz column to default ‘mz’ but the other three to values different than default :
```
raw_file_name_preparelibrary_pos_msnbase = 'RAW_FILE'
compund_id_preparelibrary_pos_msnbase = 'IARC_ID'
compound_name_preparelibrary_pos_msnbase = 'NAME'
mz_col_preparelibrary_pos_msnbase = 'mz'
```
the process _process_create_library_pos_msnbase_ also fails but with a different error :
```
  Loading required package: stringr
  Error in data.frame(startRT = startRT, endRT = endRT, startMZ = startMZ,  : 
    arguments imply differing number of rows: 1, 0
  Calls: createLibrary -> IntervalMerge -> data.frame
  Execution halted
```
 
When we set all the four parameters to their default values :
```
raw_file_name_preparelibrary_pos_msnbase = ‘rawFile’
compound_id_preparelibrary_pos_msnbase = ‘HMDB.YMDB.ID’
compound_name_preparelibrary_pos_msnbase = ‘PRIMARY_NAME’
mz_col_preparelibrary_pos_msnbase = ‘mz’
```
the process succeeds for a few tasks (for a few identification file), but fails for others, giving the following error :
```
Loading required package: stringr
Error in strsplit(x = hitTMP[, "parentmzs"], split = ";", fixed = T)[[1]] : 
  subscript out of bounds
Calls: createLibrary
Execution halted
```
 
In the [bin](https://github.com/nf-core/metaboigniter/tree/master/bin) folder, I dug into the R scripts involved in the process _process_create_library_pos_msnbase_ ([_createLibrary.R_](https://github.com/nf-core/metaboigniter/blob/master/bin/createLibrary.r) and [_createLibraryFun.R_](https://github.com/nf-core/metaboigniter/blob/master/bin/createLibraryFun.r)) and found that it is related to the dataframe [_MSlibrary_](https://github.com/nf-core/metaboigniter/blob/master/bin/createLibraryFun.r#L170-L175) in the script [_createLibraryFun.R_](https://github.com/nf-core/metaboigniter/blob/master/bin/createLibraryFun.r). For the tasks failing, in the dataframe _MSlibrary_, the columns _parentmzs_, _parentrts_, _parentInts_ and _MS2s_ are empty, therefore the line `MSlibrary[MSlibrary[,"MS2s"]!="",]` returns an empty dataframe and further creates an empty [hitTMP](https://github.com/nf-core/metaboigniter/blob/master/bin/createLibraryFun.r#L179) dataframe. While for tasks succeeding, these columns are not empty, giving further a non-empty hitTMP dataframe !

I still can’t understand what could have happened leading to this issue 😢 
 
If you have any idea that would be great !
Once again thank you so much in advance for your answer 💪

**Comment by PayamEmami** [comment]
Thanks for the report. This has been fixed now in the latest dev version.
