### ISSUE TITLE
Process to create library using MSnbase fails on a few files

### ISSUE THREAD

**Issue by maxvincent24** [nf-core/metaboigniter#50]
## Description of the bug

In the identification subpipeline, I am trying to perform the identification using internal standards. I have a few library .mzML files and an associated library description file. The process _process_create_library_pos_msnbase_ fails for some of the files but pass for some others

## Steps to reproduce

Steps to reproduce the behaviour:

Sorry the data cannot be provided to reproduce the error :(

1. Command line: `nextflow run metaboigniter/main.nf -c metaboigniter/conf/custom.config -profile singularity`

2. System:
- Hardware: HPC
- Executor: slurm
- OS: CentOS Linux
- Version: 7

3. Nextflow Installation:
- Version: 20.10.0

4. Container engine:
- Engine: Singularity
- version: 3.7.4-1.el7
- Image tag: nfcore/metaboigniter:dev

## Errors

Before the latest dev version, the process _process_create_library_pos_msnbase_ failed on some of my library files, but the error was not the same for all these files, either this error (A) :
```
Error in strsplit(x = hitTMP[, "parentmzs"], split = ";", fixed = T)[[1]] : 
  subscript out of bounds
Calls: createLibrary
Execution halted
```
or this error (B) :
```
Error in parentMS2s[[p]] : subscript out of bounds
Calls: createLibrary
Execution halted
```

In the latest dev version [(9c86f6f)](https://github.com/nf-core/metaboigniter/commit/9c86f6f9f613db56f6f324d1fba3a0d8849f7ad2), with the modifications in the [createLibrary.R](https://github.com/nf-core/metaboigniter/blob/master/bin/createLibrary.r) file, the files which failed with error B (_Error in parentMS2s[[p]] : subscript out of bounds_) now pass this process, but the files which failed with error A (_Error in strsplit(x = hitTMP[, "parentmzs"], split = ";", fixed = T)[[1]] : subscript out of bounds_) still fail

If you have any idea on this issue it would be of great help 💪 
Thanks in advance

**Comment by PayamEmami** [comment]
This has now been fixed by the last PR
