### ISSUE TITLE
Software in bioconda

### ISSUE THREAD

**Issue by ewels** [nf-core/metaboigniter#6]
Generally we aim to use software packaged in BioConda for nf-core pipelines. By doing so we get support for conda, docker and singularity (the 2nd two via https://biocontainers.pro). We also avoid taking on maintenance of software packaging as well as pipeline maintenance.

Currently, this pipeline is using a suite of custom Docker containers. These are all built using dedicated repos at https://github.com/MetaboIGNITER 

If possible, it would be great to switch from using these to using Bioconda. Here's my quick googling for them:

* [x] `metaboigniter/container-openms:v2.4.0` - Yes: [`openms`](https://bioconda.github.io/recipes/openms-meta/README.html#package-openms) / [`openms-thirdparty`](https://bioconda.github.io/recipes/openms-meta/README.html#package-openms-thirdparty)
  * The [nf-core/mhcquant](https://github.com/nf-core/mhcquant) pipeline seems to [use the latter](https://github.com/nf-core/mhcquant/blob/3437540db07a1b51e6b88bcb41a5c8c6844bf283/environment.yml#L12)
* [ ] `metaboigniter/container-openmstoxcms:v1.0.1` - Maybe as part of the packages above?
* [x] `metaboigniter/container-xcms:v3.0.2_ipo` - Yes: [`bioconductor-xcms`](https://bioconda.github.io/recipes/bioconductor-xcms/README.html#package-bioconductor-xcms)
* [x] `metaboigniter/container-camera:v1.33.4_xcms3.0.2` - Yes: [`bioconductor-camera`](https://bioconda.github.io/recipes/bioconductor-camera/README.html#package-bioconductor-camera)
* [x] `metaboigniter/container-msnbase:v2.0.2` - Yes: [`bioconductor-msnbase`](https://bioconda.github.io/recipes/bioconductor-msnbase/README.html#package-bioconductor-msnbase)
* [x] `metaboigniter/container-metfrag:v0.0.1` - Yes: [`metfrag`](https://bioconda.github.io/recipes/metfrag/README.html#package-metfrag)
* [ ] `metaboigniter/container-cfmid:v2.0.2` - No
* [x] `metaboigniter/container-csifingerid:v4.5.1_v1` - Yes: [`sirius-csifingerid`](https://bioconda.github.io/recipes/sirius-csifingerid/README.html#package-sirius-csifingerid)
* [ ] `metaboigniter/container-passatutto:v2.1.0` - No

So nearly all seem to be available already on the face of it.

As you're currently using one container per process, the quickest way to use them is just to add them to the main script, e.g.:

```nextflow
process xcms {
    container "quay.io/biocontainers/bioconductor-xcms:3.12.0--r40h5f743cb_0"
    conda "bioconductor-xcms:3.12.0-0"

    script:
    """
    normal nextflow stuff here
    """
}
```

However, if it works, it might be nicer to add an `environment.yml` file back with the bioconda deps in, if they play well together. That gives a couple of advantages:

* We can make the `get_software_versions` process run each command in one process to get the software version numbers reported
* Simpler administration - `nf-core lint` checks this file for available updates for example
* Smaller total file size for Singularity users

If they don't work together then that's fine. Pretty soon we will be moving all pipelines to DSL2 and rewriting pipelines to use a central repository of software wrappers at https://github.com/nf-core/modules - then each process will have to have its own container. If we're not using the main pipeline docker image at all we should delete the `Dockerfile` though and remove mention of the top-level `process.container` attribute.

Let me know what you think!

Phil

**Comment by ewels** [comment]
OpenMSToXCMS is a repo of R scripts written by @PayamEmami here: https://github.com/PayamEmami/OpenMSToXCMS - these could either be bundled in the pipeline `bin` directory directly or packaged, ideally into Bioconductor (which will then eventually go -> Bioconda -> BioContainers, although that will take some time).

cfmid is here: https://cfmid.wishartlab.com/ with code here: https://bitbucket.org/wishartlab/msrb-fragmenter/src/master/ and it's also on SourceForge (🥳) https://sourceforge.net/projects/cfm-id/ - this one is just a maven Java project so should be fairly easy I _think_..

Passatutto is part of the [SIRIUS](https://bio.informatik.uni-jena.de/software/sirius/) suite but seems to have its own gradle java build settings in this subdirectory: https://github.com/boecker-lab/sirius-libs/tree/release-4.4/passatutto

**Comment by ewels** [comment]
Note for Passatutto - there are already other Sirius packages on Bioconda, eg https://bioconda.github.io/recipes/sirius-csifingerid/README.html so can hopefully model on that?

**Comment by PayamEmami** [comment]
This has been done now in the DSL2 version.
