### ISSUE TITLE
Filename too long error when aligning multiple files

### ISSUE THREAD

**Issue by plashmore** [nf-core/metaboigniter#85]
### Description of the bug

metaboigniter completes without error when running only a couple files, but when running a full batch (63 files) crashes at the alignment step giving a "filename too long" error when trying to create the output from the mapalign step. it looks as though it's trying to pass an array of sample names as a filename to the /alignment/ folder.

### Command used and terminal output

```console
command: nextflow run nf-core/metaboigniter -profile docker

output: Mar-01 19:13:26.604 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: /home/laytox/projects/smoke/smoke_taint/99-output/alignment/[c3r1-r001, c3r1-r002, c1r3-r003, c1r3-r001, c3r1-r003, c1r1-r002, c1r1-r003, c1r1-r001, c1r3-r002, c3r3-r001, c3r3-r002, c4r1-r001, c3r3-r003, c4r1-r002, s1r1-r001, c4r1-r003, c4r3-r002, c4r3-r003, c4r3-r001, s1r1-r002, s1r2-r001, s1r1-r003, s1r2-r002, s1r2-r003, s1r3-r001, s2r1-r001, s1r3-r002, s1r3-r003, s2r3-r001, s2r1-r002, s2r1-r003, s2r2-r001, s2r2-r003, s2r2-r002, s3r1-r003, s2r3-r002, s2r3-r003, s3r1-r001, s3r3-r001, s3r1-r002, s3r2-r001, s3r2-r002, s3r2-r003, s3r3-r002, s4br2-r001, s3r3-r003, s4br1-r001, s4br1-r002, s4br1-r003, s4br3-r003, s4br2-r002, s4br2-r003, s4br3-r001, s4br3-r002, s4fr2-r001, s4fr1-r001, s4fr3-r001, s4fr1-r002, s4fr1-r003, s4fr2-r002, s4fr2-r003, s4fr3-r002, s4fr3-r003]: File name too long
```

### Relevant files

[files.zip](https://github.com/nf-core/metaboigniter/files/14470257/files.zip)

### System information

Nextflow version: 23.10.1
Metaboigniter version: 2.0.0
Hardware: desktop
Executor: local
container engine: docker
OS: Linux (Fedora 39)

**Comment by YoujiaMa** [comment]
@plashmore hi, u can try change the code
https://github.com/nf-core/metaboigniter/blob/master/conf/modules.config#L137
https://github.com/nf-core/metaboigniter/blob/master/conf/modules.config#L175
```
path: { "${params.outdir}/alignment" },
```

**Comment by plashmore** [comment]
that appears to have worked, thanks!

**Comment by plashmore** [comment]
getting a new error now, don't know if it's related or not, but i changed the config to allow centroiding of data files and get an error after the first file saying "missing output file(s) 'output/*.centroided.mzML' expected by process"
