### ISSUE TITLE
No `siriussearch.sh` in the docker -- `quay.io/biocontainers/sirius-csifingerid:5.8.6--h3bb291f_0`

### ISSUE THREAD

**Issue by liangyong1991** [nf-core/metaboigniter#93]
### Description of the bug

When I was testing the pipeline, `siriussearch.sh` can not be found in the docker image `quay.io/biocontainers/sirius-csifingerid:5.8.6--h3bb291f_0`. Instead, it can be found at `metaboigniter/bin/siriussearch.sh`.

**Comment by YoujiaMa** [comment]
@liangyong1991 When use nextflow, _siriussearch.sh_ is automatically mounted to the container

**Comment by PayamEmami** [comment]
as @YoujiaMa said, these are customized scripts to prepare, run and parse SIRIUS. SIRIUS biocontainers are managed by SIRIUS developers, not us.
