### ISSUE TITLE
Maximum number of CPUs

### ISSUE THREAD

**Issue by mvisani** [nf-core/metaboigniter#94]
### Description of the bug

Maximal number of CPUs doesn't go over 12 even when though I set it to 32 `max_cpus`in my config file. 

### Relevant files
<img width="1077" alt="Screenshot 2024-04-22 at 17 21 49" src="https://github.com/nf-core/metaboigniter/assets/92217074/327b04f5-dc61-4687-8bec-715dbd4ee7bf">

### System information

- Nextflow version 23.10.1.5891
- Desktop computer with 64 core CPUs, 252GB RAM
- Executor : local
- Container : Docker
- OS : Ubuntu 22.04.4 LTS
- Metaboigniter version : 2.0.1

**Comment by PayamEmami** [comment]
Hello,

`max_cpus` put the higher limit on the number of CPUs  not the number used in each process. 
You need to check the CPUs here In the `base.config`. 

https://github.com/nf-core/metaboigniter/blob/master/conf/base.config

For example `OPENMS_FEATURELINKERUNLABELEDKD` has been set as high usage (`process_high`). So you would need to change this part:
```
withLabel:process_high {
        cpus   = { check_max( 12    * task.attempt, 'cpus'    ) }
        memory = { check_max( 84.GB * task.attempt, 'memory'  ) }
        time   = { check_max( 16.h  * task.attempt, 'time'    ) }
    }
```

I hope it helps.
