### ISSUE TITLE
Local MGF library

### ISSUE THREAD

**Issue by mansoldof** [nf-core/metaboigniter#99]
### Description of feature

Hi,
is it possible to setup a local library MGF file for annotation?
thanks

**Comment by PayamEmami** [comment]
Hello,

I'm sorry for not getting back to you sooner. It is possible to train MS2Query using in-house MGF file. 
You can set `train_library_ms2query` and pass an annotated MGF file using `library_path_ms2query`. The annotation will still be performed using the MS2 data. 

For the format of MGF file look here: https://github.com/iomega/ms2query/blob/main/dummy_data/dummy_spectra.mgf

Best
Payam

**Comment by mansoldof** [comment]
That's great,
thanks
